# name: (path regex, version regex, upstream repo, tag format)
# version regex groups are joined with "." when they are all numbers
LIBS = {
    'zlib': (r'(^|/)zlib\.h$', r'#define\s+ZLIB_VERSION\s+"([^"]+)"',
             'https://github.com/madler/zlib', 'v{}'),
    'sqlite': (r'(^|/)sqlite3\.h$', r'#define\s+SQLITE_VERSION\s+"([^"]+)"',
               'https://github.com/sqlite/sqlite', 'version-{}'),
    'libxml2': (r'(^|/)xmlversion\.h$', r'#define\s+LIBXML_DOTTED_VERSION\s+"([^"]+)"',
                'https://gitlab.gnome.org/GNOME/libxml2', 'v{}'),
    'expat': (r'(^|/)expat\.h$',
              r'XML_MAJOR_VERSION\s+(\d+)\s*\n#define\s+XML_MINOR_VERSION\s+(\d+)\s*\n#define\s+XML_MICRO_VERSION\s+(\d+)',
              'https://github.com/libexpat/libexpat', 'R_{}'),
    'libpng': (r'(^|/)png\.h$', r'#define\s+PNG_LIBPNG_VER_STRING\s+"([^"]+)"',
               'https://github.com/pnggroup/libpng', 'v{}'),
    'libjpeg-turbo': (r'(^|/)jversion\.h$', r'#define\s+JVERSION\s+"([\d.]+)',
                      'https://github.com/libjpeg-turbo/libjpeg-turbo', '{}'),
    'bzip2': (r'(^|/)bzlib_private\.h$', r'#define\s+BZ_VERSION\s+"([\d.]+)',
              'https://gitlab.com/bzip2/bzip2', 'bzip2-{}'),
    'lz4': (r'(^|/)lz4\.h$',
            r'LZ4_VERSION_MAJOR\s+(\d+).*?\n#define\s+LZ4_VERSION_MINOR\s+(\d+).*?\n#define\s+LZ4_VERSION_RELEASE\s+(\d+)',
            'https://github.com/lz4/lz4', 'v{}'),
    'zstd': (r'(^|/)zstd\.h$',
             r'ZSTD_VERSION_MAJOR\s+(\d+)\s*\n#define\s+ZSTD_VERSION_MINOR\s+(\d+)\s*\n#define\s+ZSTD_VERSION_RELEASE\s+(\d+)',
             'https://github.com/facebook/zstd', 'v{}'),
    'pcre2': (r'(^|/)pcre2\.h(\.in|\.generic)?$', r'PCRE2_MAJOR\s+(\d+)\s*\n#define\s+PCRE2_MINOR\s+(\d+)',
              'https://github.com/PCRE2Project/pcre2', 'pcre2-{}'),
    'libuv': (r'(^|/)uv/version\.h$',
              r'UV_VERSION_MAJOR\s+(\d+)\s*\n#define\s+UV_VERSION_MINOR\s+(\d+)\s*\n#define\s+UV_VERSION_PATCH\s+(\d+)',
              'https://github.com/libuv/libuv', 'v{}'),
    'yajl': (r'(^|/)yajl_version\.h$',
             r'YAJL_MAJOR\s+(\d+)\s*\n#define\s+YAJL_MINOR\s+(\d+)\s*\n#define\s+YAJL_MICRO\s+(\d+)',
             'https://github.com/lloyd/yajl', '{}'),
    'cmark-gfm': (r'(^|/)cmark(-gfm)?_version\.h$', r'CMARK(?:_GFM)?_VERSION_STRING\s+"([^"]+)"',
                  'https://github.com/github/cmark-gfm', '{}'),
    # libxls keeps its version in config.h, xls.h only proves it's there
    'libxls': (r'(^|/)xls\.h$', None, 'https://github.com/libxls/libxls', 'v{}'),
    'ReadStat': (r'(^|/)readstat\.h$', None, 'https://github.com/WizardMac/ReadStat', 'v{}'),
    'igraph': (r'(^|/)igraph_version\.h$', r'#define\s+IGRAPH_VERSION\s+"([^"]+)"',
               'https://github.com/igraph/igraph', '{}'),
    'mbedtls': (r'(^|/)mbedtls/(build_info|version)\.h$', r'MBEDTLS_VERSION_STRING\s+"([^"]+)"',
                'https://github.com/Mbed-TLS/mbedtls', 'mbedtls-{}'),
    'libgit2': (r'(^|/)git2/version\.h$', r'#define\s+LIBGIT2_VERSION\s+"([^"]+)"',
                'https://github.com/libgit2/libgit2', 'v{}'),
    'libyaml': (r'(^|/)yaml\.h$', None, 'https://github.com/yaml/libyaml', '{}'),
    'miniz': (r'(^|/)miniz\.h$', r'#define\s+MZ_VERSION\s+"([^"]+)"', None, None),
}

# js banner: "plotly.js v2.11.1", "pym.js - v1.3.1", "jQuery v3.6.0" ...
JS_BANNER = r'([A-Za-z][\w.\-]*?(?:\.js)?)\s*(?:-\s*)?v(\d+\.\d+\.\d+)'
